// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureSelection():Promise<string>;

export function LoadConfig():Promise<string>;

export function RecognizeText(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function TranslateText(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function TranslateWithOpenAI(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;
