// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureSelection() {
  return window['go']['backend']['App']['CaptureSelection']();
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function RecognizeText(arg1, arg2) {
  return window['go']['backend']['App']['RecognizeText'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function TranslateText(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backend']['App']['TranslateText'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TranslateWithOpenAI(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['TranslateWithOpenAI'](arg1, arg2, arg3, arg4, arg5, arg6);
}
